# -*- coding: utf-8 -*-
"""used-car-pricing-strategy-simulator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HORQn0BZEK5sCjj2_9_RuNG9a4N_HSBn

# Dynamic Vehicle Pricing and Days-on-Market Optimization

## Business Problem
In used car marketplaces, sellers often struggle to determine the right listing price. If the price is too high, the vehicle may stay on the platform for too long. If the price is too low, the seller may lose potential revenue. Therefore, a data-driven pricing decision system is needed to balance selling speed and price optimization.

## Objective
The aim of this project is to build a decision-support system that:
1. predicts the fair market price of a used vehicle,
2. estimates how different pricing scenarios may affect time-to-sell,
3. recommends pricing strategies for fast sale, balanced sale, and maximum revenue.

## Expected Output
For a given vehicle, the system should provide:
- estimated fair market value,
- expected selling speed under different price levels,
- pricing recommendations based on different seller priorities.

## Business Value
This project can help:
- sellers make more informed pricing decisions,
- platforms improve listing quality,
- users achieve faster and more balanced sales outcomes.

## Out of Scope
This project does not include:
- computer vision,
- image-based damage detection,
- deep learning on vehicle photos.

The current scope focuses only on structured/tabular vehicle listing data.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings

warnings.filterwarnings('ignore')
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows",100)
pd.set_option("display.float_format",lambda x: f"{x:,.2f}")

df = pd.read_csv("/content/sample_data/temizlenmis_otomobil_verisi.csv")
df.head()

df.shape

df.columns.tolist()

df.info()

df.isnull().sum().sort_values(ascending=False)

df.describe().T

df.nunique().sort_values(ascending=False)

df.duplicated().sum()

df[df["kilometre"] == 0].shape[0]

df[df["kilometre"] == 0].head(10)

df[df["fiyat"] < 100000].sort_values("fiyat").head(20)

df[df["fiyat"] > 5000000].sort_values("fiyat",ascending=False).head(20)

plt.figure(figsize=(10,5))
plt.hist(df["fiyat"],bins=50)
plt.title("Distribution of Vehicle Prices")
plt.xlabel("Fiyat")
plt.ylabel("Araç Sayısı")
plt.show()

plt.figure(figsize=(10,5))
plt.hist(np.log1p(df["fiyat"]),bins=50)
plt.title("Distribution of Log-Transformed Vehicle Prices")
plt.xlabel("Log Fiyat")
plt.ylabel("Araç Sayısı")
plt.show()

df_clean = df.drop_duplicates().reset_index(drop=True)
print("Orjinal Veri Boyutu:",df.shape)
print("Temiz Veri Boyutu:",df_clean.shape)
print("Silinen Tekrar Sayısı:",df.shape[0]-df_clean.shape[0])

REFERENCE_YEAR = df_clean["yil"].max()
df_clean["arac_yasi"] = REFERENCE_YEAR - df_clean["yil"]
df_clean["km_yillik"] = df_clean["kilometre"] / (df_clean["arac_yasi"] + 1)
df_clean["hasar_toplam"] = df_clean["degisen_sayisi"] + df_clean["boyali_sayisi"]
df_clean["fiyat_log"] = np.log1p(df_clean["fiyat"])
df_clean[["yil", "arac_yasi", "kilometre", "km_yillik", "degisen_sayisi", "boyali_sayisi", "hasar_toplam", "fiyat", "fiyat_log"]].head()

df_clean[["arac_yasi", "km_yillik", "hasar_toplam", "fiyat", "fiyat_log"]].describe().T

plt.figure(figsize=(10,5))
plt.hist(df_clean["fiyat"], bins=50)
plt.title("Fiyat Dağılımı")
plt.xlabel("Fiyat")
plt.ylabel("Araç Sayısı")
plt.show()

plt.figure(figsize=(10,5))
plt.hist(df_clean["fiyat_log"], bins=50)
plt.title("Log Fiyat Dağılımı")
plt.xlabel("Log(Fiyat)")
plt.ylabel("Araç Sayısı")
plt.show()

plt.figure(figsize=(10,5))
plt.scatter(df_clean["arac_yasi"], df_clean["fiyat"], alpha=0.3)
plt.title("Araç Yaşı ve Fiyat İlişkisi")
plt.xlabel("Araç Yaşı")
plt.ylabel("Fiyat")
plt.show()

plt.figure(figsize=(10,5))
plt.scatter(df_clean["kilometre"],df_clean["fiyat"],alpha=0.3)
plt.title("Kilometre ve Fiyat İlişkisi")
plt.xlabel("Kilometre")
plt.ylabel("Fiyat")
plt.show()

hasar_fiyat = df_clean.groupby("hasar_toplam")["fiyat"].median().reset_index()
plt.figure(figsize=(10,5))
plt.bar(hasar_fiyat["hasar_toplam"],hasar_fiyat["fiyat"])
plt.title("Hasar Toplamına Göre Medyan Fiyat")
plt.xlabel("Toplam İşlemli Parça Sayısı")
plt.ylabel("Medyan Fiyat")
plt.show()
hasar_fiyat

marka_fiyat = (
    df_clean.groupby("marka")
    .agg(
        arac_sayisi=("fiyat", "count"),
        medyan_fiyat=("fiyat", "median"),
        ortalama_fiyat=("fiyat", "mean")
    )
    .sort_values("medyan_fiyat", ascending=False)
)

marka_fiyat.head(15)

df_clean["marka"].value_counts().head(20)

df_clean.groupby("hasar_toplam")["fiyat"].median().reset_index()

"""Şimdiye kadar amacımız model kurmadan önce fiyatı etkileyebilecek değişkenleri gözlemlemek.

Ve gördük'ki;
Araç yaşı fiyatı etkiliyor.
Kilometre fiyatı etkiliyor.
Hasar toplamı fiyatı etkiliyor.
Marka fiyatı ciddi biçimde etkiliyor.
Fiyat dağılımı sağa çarpık olduğu için log dönüşüm faydalı olabilir.
"""

categorical_features = [
    "marka",
    "seri",
    "model",
    "vites_tipi",
    "yakit_tipi",
    "kasa_tipi",
    "renk",
    "kimden"
]

numeric_features = [
    "arac_yasi",
    "kilometre",
    "km_yillik",
    "motor_hacmi",
    "motor_gucu",
    "degisen_sayisi",
    "boyali_sayisi",
    "hasar_toplam"
]

feature_cols = categorical_features + numeric_features

X = df_clean[feature_cols]
y = df_clean["fiyat_log"]

print("X shape:", X.shape)
print("y shape:", y.shape)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

from sklearn.dummy import DummyRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

baseline_model = DummyRegressor(strategy="mean")

baseline_model.fit(X_train, y_train)

baseline_pred_log = baseline_model.predict(X_test)

y_test_tl = np.expm1(y_test)
baseline_pred_tl = np.expm1(baseline_pred_log)

baseline_mae = mean_absolute_error(y_test_tl, baseline_pred_tl)
baseline_rmse = np.sqrt(mean_squared_error(y_test_tl, baseline_pred_tl))
baseline_r2_log = r2_score(y_test, baseline_pred_log)

print("Baseline MAE:", round(baseline_mae, 2))
print("Baseline RMSE:", round(baseline_rmse, 2))
print("Baseline R2 on log target:", round(baseline_r2_log, 4))

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge

categorical_transformer = OneHotEncoder(handle_unknown="ignore", sparse_output=True)

numeric_transformer = StandardScaler()

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", categorical_transformer, categorical_features),
        ("num", numeric_transformer, numeric_features)
    ]
)

ridge_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", Ridge(alpha=1.0))
    ]
)

ridge_model.fit(X_train, y_train)

# One-hot encoding sonrası oluşan tüm özellik (feature) isimlerini alalım
feature_names = ridge_model.named_steps['preprocessor'].get_feature_names_out()

print(f"Başlangıçtaki sütun sayısı: {len(categorical_features) + len(numeric_features)}")
print(f"İşlem sonrası (One-Hot dahil) toplam sütun sayısı: {len(feature_names)}")
print("-" * 30)
print("İlk 20 sütun örneği:")
print(feature_names[:20])

ridge_model.fit(X_train, y_train)

ridge_pred_log = ridge_model.predict(X_test)

ridge_pred_tl = np.expm1(ridge_pred_log)
ridge_mae = mean_absolute_error(y_test_tl,ridge_pred_tl)
ridge_rmse = np.sqrt(mean_squared_error(y_test_tl,ridge_pred_tl))
ridge_r2_log = r2_score(y_test, ridge_pred_log)

print("Ridge MAE:", round(ridge_mae,2))
print("Ridge RMSE:", round(ridge_rmse,2))
print("Ridge R2 on log target:" ,round(ridge_r2_log,4))

results = pd.DataFrame({
    "Model" : ["Baseline Mean Model", "Ridge Regression"],
    "MAE_TL" : [baseline_mae,ridge_mae],
    "RMSE_TL" : [baseline_rmse,ridge_rmse],
    "r2_Log_Target" : [baseline_r2_log,ridge_r2_log]
})

results

feature_names = ridge_model.named_steps["preprocessor"].get_feature_names_out()
coefficients = ridge_model.named_steps["model"].coef_

coef_df = pd.DataFrame({
    "feature": feature_names,
    "coefficient": coefficients
})

coef_df["abs_coefficient"] = coef_df["coefficient"].abs()

coef_df.sort_values("abs_coefficient", ascending=False).head(20)

coef_df.sort_values("coefficient", ascending=True).head(20)

"""### Ridge Regression Coefficient Analysis

After training the Ridge Regression model, I analyzed the model coefficients to understand which features had the strongest positive and negative effects on the predicted log price.

Premium and performance-oriented brands or series such as Porsche, Mercedes-Benz, Maserati, Lotus, Camaro, Mustang and Corvette showed strong positive coefficients, which is consistent with the expected pricing behavior in the used car market.

On the other hand, lower-priced brands and older vehicle-related effects showed negative coefficients. In particular, vehicle age had a negative coefficient, indicating that older vehicles tend to have lower predicted prices when other variables are considered.

It is important to note that these coefficients represent effects on the log-transformed price target, not direct TL changes. Also, categorical coefficients should be interpreted within the context of the dataset and the other encoded features included in the model.
"""

from sklearn.ensemble import RandomForestRegressor

rf_model = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", RandomForestRegressor(
            n_estimators=100,
            max_depth=20,
            random_state=42,
            n_jobs=-1
        ))
    ]
)

rf_model.fit(X_train, y_train)

rf_pred_log = rf_model.predict(X_test)

rf_pred_tl = np.expm1(rf_pred_log)

rf_mae = mean_absolute_error(y_test_tl, rf_pred_tl)
rf_rmse = np.sqrt(mean_squared_error(y_test_tl, rf_pred_tl))
rf_r2_log = r2_score(y_test, rf_pred_log)

print("Random Forest MAE:", round(rf_mae, 2))
print("Random Forest RMSE:", round(rf_rmse, 2))
print("Random Forest R2 on log target:", round(rf_r2_log, 4))

results = pd.DataFrame({
    "Model": ["Baseline Mean Model", "Ridge Regression", "Random Forest"],
    "MAE_TL": [baseline_mae, ridge_mae, rf_mae],
    "RMSE_TL": [baseline_rmse, ridge_rmse, rf_rmse],
    "R2_Log_Target": [baseline_r2_log, ridge_r2_log, rf_r2_log]
})

results

plt.figure(figsize=(8,6))
plt.scatter(y_test_tl, rf_pred_tl, alpha=0.3)
plt.xlabel("Gerçek Fiyat")
plt.ylabel("Tahmin Edilen Fiyat")
plt.title("Random Forest: Gerçek Fiyat vs Tahmin Edilen Fiyat")
plt.show()

rf_feature_names = rf_model.named_steps["preprocessor"].get_feature_names_out()
rf_importances = rf_model.named_steps["model"].feature_importances_

rf_importance_df = pd.DataFrame({
    "feature": rf_feature_names,
    "importance": rf_importances
}).sort_values("importance", ascending=False)

rf_importance_df.head(20)

"""# Pricing Strategy Simulator

In this section, I extend the price prediction model into a pricing decision-support tool.

Instead of only predicting a single vehicle price, the simulator generates different pricing strategies based on the predicted fair market value:

- Fast Sale Price: A lower price scenario for faster selling potential.
- Balanced Price: The predicted fair market value.
- Max Revenue Price: A higher price scenario for sellers who prioritize revenue over speed.

This section aims to transform the machine learning model into a more business-oriented pricing support system.
"""

sample_car = X_test.sample(1, random_state=42)
sample_car

sample_pred_log = ridge_model.predict(sample_car)
sample_pred_price = np.expm1(sample_pred_log)[0]
print("Tahmini Piyasa Fiyatı:", round(sample_pred_price, 2), "TL")

fast_sale_price = sample_pred_price * 0.95
balanced_price = sample_pred_price
max_revenue_price = sample_pred_price * 1.05

pricing_strategy = pd.DataFrame({
    "Strategy": ["Fast Sale", "Balanced", "Max Revenue"],
    "Recommended_Price_TL": [
        fast_sale_price,
        balanced_price,
        max_revenue_price
    ],
    "Description": [
        "Lower price scenario for faster selling potential",
        "Estimated fair market value",
        "Higher price scenario for revenue-focused sellers"
    ]
})

pricing_strategy

pricing_strategy["Recommended_Price_TL"] = pricing_strategy["Recommended_Price_TL"].round(0).astype(int)

pricing_strategy

print("Vehicle Pricing Strategy Recommendation")
print("-" * 45)
print(f"Predicted Fair Market Price: {balanced_price:,.0f} TL")
print(f"Fast Sale Price: {fast_sale_price:,.0f} TL")
print(f"Balanced Price: {balanced_price:,.0f} TL")
print(f"Max Revenue Price: {max_revenue_price:,.0f} TL")

#Since the dataset does not include actual time-to-sell information, the pricing strategies are generated as scenario-based recommendations around the predicted fair market value.

sample_car.iloc[0]

sample_row = sample_car.iloc[0]

similar_cars = df_clean[
    (df_clean["marka"] == sample_row["marka"]) &
    (df_clean["seri"] == sample_row["seri"]) &
    (df_clean["vites_tipi"] == sample_row["vites_tipi"]) &
    (df_clean["yakit_tipi"] == sample_row["yakit_tipi"])
]

print("Benzer araç sayısı:", similar_cars.shape[0])
similar_cars[["marka", "seri", "model", "yil", "kilometre", "fiyat"]].head(10)

similar_summary = similar_cars["fiyat"].describe()
similar_summary

similar_median_price = similar_cars["fiyat"].median()

print("Benzer Araç Medyan Fiyatı:", f"{similar_median_price:,.0f} TL")
print("Model Tahmini Piyasa Fiyatı:", f"{sample_pred_price:,.0f} TL")

lower_bound = similar_median_price * 0.95
upper_bound = similar_median_price * 1.05

if sample_pred_price < lower_bound:
    market_position = "Below Market"
elif sample_pred_price > upper_bound:
    market_position = "Above Market"
else:
    market_position = "At Market"

print("Market Position:", market_position)
print("Lower Bound:", f"{lower_bound:,.0f} TL")
print("Upper Bound:", f"{upper_bound:,.0f} TL")

print("Vehicle Pricing Strategy Recommendation")
print("-" * 50)
print(f"Predicted Fair Market Price: {balanced_price:,.0f} TL")
print(f"Fast Sale Price: {fast_sale_price:,.0f} TL")
print(f"Balanced Price: {balanced_price:,.0f} TL")
print(f"Max Revenue Price: {max_revenue_price:,.0f} TL")
print(f"Market Position vs Similar Vehicles: {market_position}")
print(f"Similar Vehicles Median Price: {similar_median_price:,.0f} TL")

